/**
 * @description       : Test for {{CLASS_NAME}}
 * @author            : andrii.solokh@wipro.com
 * @group             : Core.Test
 * @last modified on  : 04-30-2023
 * @last modified by  : andrii.solokh@wipro.com
 **/

@IsTest
public class {{CLASS_NAME}} {

    @TestSetup
    public static void setup(){
    }
    
    @IsTest
    public static void handleRecordUpdate(){
        Test.start();
        Test.stop();
    }
}